name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Read version from README
        id: read_version
        run: |
          VERSION=$(grep -m 1 '^# YT QOL' README.md | awk '{print $4}')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Update version in package.json
        run: |
          jq --arg ver "$version" '.version = $ver' package.json > package.tmp.json
          mv package.tmp.json package.json
          echo "Updated package.json version to $version"

      - name: Update version in manifest.json
        run: |
          jq --arg ver "$version" '.version = $ver' manifest.json > manifest.tmp.json
          mv manifest.tmp.json manifest.json
          echo "Updated manifest.json version to $version"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Version ${{ env.version }}
          tag_name: ${{ env.version }}
          body_path: release.txt
          draft: false
          prerelease: false
          files: yt-qol.zip
